# Generated by Django 3.2.5 on 2021-07-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_apirequests_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='body',
        ),
    ]
