# Generated by Django 3.2.5 on 2021-07-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_collection_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequests',
            old_name='request',
            new_name='request_data',
        ),
    ]
