# Generated by Django 3.2.5 on 2021-07-30 18:11

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_apirequests_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequests',
            name='request_data',
            field=models.JSONField(default=collection.models.jsonfield_default_value),
        ),
    ]
