# Generated by Django 3.2.5 on 2021-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_apirequests_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequests',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
