# Generated by Django 3.2.5 on 2021-07-30 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0008_alter_apirequests_request_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIRequests',
            new_name='APIRequest',
        ),
    ]
