# Generated by Django 3.2.5 on 2021-07-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_rename_apirequests_apirequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='request_data',
            new_name='request_body',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='request_header',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
